language: python

branches:
  only:
  - master
  - dev
  - develop
  - travis_ci
  - rework_error_handling
  - add_windows_to_travis

virtualenv:
  system_site_packages: true

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
          - pstoedit
          - pdf2svg
          - inkscape
          - python-gtk2-dev
          - imagemagick
          - texlive-latex-base

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - pstoedit
          - pdf2svg
          - inkscape
          - python-gtk2-dev
          - imagemagick
          - texlive-latex-base
    - os: windows
        before_install:
          - choco install pdf2svg
          - choco install ghostscript
          - choco install python2
          - choco install pygtk-all-in-one_win32_py2.7
          - choco install inkscape
          - choco install miktex
          - export PATH="/c/Python27:$PATH"

before_script:
   - python2 -m pip install pytest lxml Pillow
   - python2 test_installation_script.py 2> /dev/null
   - python3 test_installation_script.py 2> /dev/null # also test python3 as installer
   - python2 setup.py


script:
  - export PYTHONPATH="`inkscape -x`:$HOME/.config/inkscape/extensions/"
  - python2 -m pytest --verbose -s pytests


